[package]
name = "simplex-noise"
version = "0.1.0"
authors = ["koehr <n@koehr.in>"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "*"
wasm-bindgen = "0.2"
rand = "0.4"
